// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ExampleApp",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ExampleApp",
            targets: ["AppModule"],
            bundleIdentifier: "com.kokiTakashiki.ExampleApp",
            teamIdentifier: "GY636G2259",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "../..")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "UnsplashPhotoPicker", package: "unsplash-photopicker-ios"),
                .product(name: "UnsplashPhotoPickerUI_iOS", package: "unsplash-photopicker-ios")
            ],
            path: "."
        )
    ]
)